version: '3'
services:
  web:
    container_name: dev-nginx
    image: dev-nginx:v1
    ports:
       - "80:80"
    volumes:
       - ./src/:/home/ibtikar/public_html/
       - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./conf/nginx/conf.d/:/etc/nginx/conf.d/
    restart: always
    depends_on:
        - php-71
        - php-56
        - db

  php-71:
    container_name: fpm-71
    image: php-fpm-71:v1
    volumes:
        - ./src/:/home/ibtikar/public_html/
    restart: always
    depends_on:
        - db

  php-56:
    container_name: fpm-56
    image: php-fpm-56:v1
    volumes:
        - ./src/:/home/ibtikar/public_html/
    restart: always
    depends_on:
        - db

  db:
    container_name: dev-mariadb
    image: mariadb:10.1
    restart: always
    volumes:
       - datacontainer:/var/lib/mysql
       - ./conf/mysql/:/etc/mysql/
    environment:
       - MYSQL_ROOT_PASSWORD=w@e5US
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

volumes:
  datacontainer:
